=== Malmo-Skyttegille-Pistolsektionen/rotation_target_backend_resources/openapi/program.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "program.schema.json",
  "title": "Program",
  "type": "object",
  "required": [
    "id",
    "title",
    "description",
    "readonly",
    "series"
  ],
  "properties": {
    "id": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "readonly": {
      "type": "boolean"
    },
    "series": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Series"
      }
    }
  },
  "$defs": {
    "Series": {
      "type": "object",
      "required": [
        "name",
        "optional", 
        "events"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "optional": {
          "type": "boolean",
          "default": false
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Event"
          }
        }
      }
    },
    "Event": {
      "type": "object",
      "required": [
        "duration"
      ],
      "properties": {
        "duration": {
          "type": "integer",
          "description": "Duration of the event in tenths of a second. For example: 1 = 0.1s, 2 = 0.2s, ..., 10 = 1.0s"
        },
        "command": {
          "type": "string"
        },
        "audio_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "List of audio IDs associated with the event."
        },
        "target_system": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "List of target system IDs associated with the event. If not specified, all target systems are affected."
        },
        "start": {
          "type": "boolean",
          "description": "Marks this event as the starting event in the series. Only one event per series may have start=true."
        }
      }
    }
  }
}

=== Malmo-Skyttegille-Pistolsektionen/rotation_target_backend_resources/programs/2.json
{
    "readonly": false,
    "description": "Match with 10 second exposure time and 10 series",
    "series": [
        {
            "optional": false,
            "name": "10s Series 1",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": false,
            "name": "10s Series 2",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": false,
            "name": "10s Series 3",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": false,
            "name": "10s Series 4",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": true,
            "name": "10s Series 5",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": true,
            "name": "10s Series 6",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": true,
            "name": "10s Series 7",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": true,
            "name": "10s Series 8",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": true,
            "name": "10s Series 9",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        },
        {
            "optional": true,
            "name": "10s Series 10",
            "events": [
                {
                    "duration": 60000,
                    "audio_ids": [
                        1
                    ],
                    "command": "show"
                },
                {
                    "command": "hide",
                    "duration": 7000
                },
                {
                    "command": "show",
                    "duration": 10000
                },
                {
                    "command": "hide",
                    "duration": 1000
                },
                {
                    "audio_ids": [
                        1
                    ],
                    "duration": 3000
                },
                {
                    "command": "show",
                    "duration": 1000
                }
            ]
        }
    ],
    "id": 102,
    "title": "Militär Snabbmatch 10s"
}

=== Malmo-Skyttegille-Pistolsektionen/rotation_target_backend_resources/programs/files/100.json
{
  "id": 100,
  "title": "Militär Snabbmatch (Klubbmästerskap)",
  "description": "Provserie 10s, 10s x 2 (+1), 8s x 2 (+1), 6s x 2 (+1)",
  "readonly": true,
  "series": [
    {
      "name": "Provserie 10s",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            50,
            1,
            28
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "10s Serie 1",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            64
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "10s Serie 2",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            65
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Färdigskjutning 1, 10 sekunder",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            84
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 10000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "8s Serie 1",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            68
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 8000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "8s Serie 2",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            69
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 8000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Färdigskjutning 1, 8 sekunder",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            86
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 8000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "6s Serie 1",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            72
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 6000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "6s Serie 2",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            73
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 6000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    },
    {
      "name": "Färdigskjutning 1, 6 sekunder",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            88
          ],
          "command": "show"
        },
        {
          "duration": 60000,
          "audio_ids": [
            26
          ],
          "command": "show"
        },
        {
          "duration": 7000,
          "command": "hide",
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 6000,
          "command": "show"
        },
        {
          "duration": 1000,
          "command": "hide"
        },
        {
          "duration": 3000,
          "audio_ids": [
            34
          ]
        },
        {
          "duration": 1000,
          "command": "show",
          "audio_ids": [
            37,
            36,
            39
          ]
        }
      ]
    }
  ]
}

=== Malmo-Skyttegille-Pistolsektionen/rotation_target_backend_resources/programs/files/20.json
{
  "id": 20,
  "title": "Precision",
  "description": "Precision 1 + 7 ( + 3 )",
  "readonly": true,
  "series": [
    {
      "name": "Provserie",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            50
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 1 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 2 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 3 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 4 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 5 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 6 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 7 5min",
      "optional": false,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 8 5min",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 9 5min",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    },
    {
      "name": "Serie 10 5min",
      "optional": true,
      "events": [
        {
          "duration": 5000,
          "audio_ids": [
            1
          ]
        },
        {
          "duration": 57000,
          "audio_ids": [
            26
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            31
          ]
        },
        {
          "duration": 297000,
          "audio_ids": [
            33
          ]
        },
        {
          "duration": 3000,
          "audio_ids": [
            35
          ]
        },
        {
          "duration": 1000,
          "audio_ids": [
            37,
            39
          ]
        }
      ]
    }
  ]
}
